version: "3"
services:
  classroom-community:
    image: classroom-community
    ports:
      - "8080:8080"
    networks:
      - classroom-community-mysql
    depends_on:
      - dbserver

  dbserver:
    image: mysql:8
    networks:
      - classroom-community-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=classroom_community_dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

networks:
  classroom-community-mysql:
